name: Feature Acceptance Test Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/**'
      - 'apps/**'
      - 'sandboxes/**'
      - 'src/**'

jobs:
  check-acceptance-tests:
    runs-on: ubuntu-latest
    name: Verify Acceptance Test Coverage
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for matrix changes
        id: matrix-changes
        run: |
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -E "packages|apps|sandboxes|src"; then
            echo "has_code_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_code_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Verify acceptance test requirements
        if: steps.matrix-changes.outputs.has_code_changes == 'true'
        run: |
          echo "🔍 Checking acceptance test requirements..."
          
          # Check if hostile-path-matrix.yaml was updated
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "docs/hostile-path-matrix.yaml"; then
            echo "✅ Matrix file updated"
          else
            echo "❌ ERROR: Code changes detected but hostile-path-matrix.yaml not updated"
            echo ""
            echo "All code changes affecting provenance verification MUST include"
            echo "corresponding acceptance test scenarios in the matrix."
            echo ""
            echo "See docs/feature-policy.md for complete requirements."
            exit 1
          fi
          
          # Check if new scenarios were added
          MATRIX_DIFF=$(git diff origin/${{ github.base_ref }}..HEAD docs/hostile-path-matrix.yaml)
          if echo "$MATRIX_DIFF" | grep -q "^\+.*id:"; then
            NEW_SCENARIOS=$(echo "$MATRIX_DIFF" | grep "^\+.*id:" | wc -l)
            echo "✅ Added $NEW_SCENARIOS new test scenarios"
          else
            echo "⚠️  WARNING: No new test scenarios detected in matrix"
            echo "Please verify your changes don't affect survival behavior"
          fi
          
          # Validate matrix syntax
          if python3 -c "import yaml; yaml.safe_load(open('docs/hostile-path-matrix.yaml'))"; then
            echo "✅ Matrix syntax is valid"
          else
            echo "❌ ERROR: Matrix file has invalid YAML syntax"
            exit 1
          fi
          
          echo ""
          echo "🎯 Feature acceptance test requirements verified!"
          echo "📋 See docs/feature-policy.md for complete guidelines"
